variables:
  tenant_id: 'e307563d-5fcd-4e12-a554-9927f388b1cf'
  subscription_id: '8c3798d4-ed62-4543-84fc-157911905c8e'
  application_id: ''
  azureml_datastore: 'imaging_datalake_poc'
  resource_group: 'rg-innereye'
  docker_shm_size: '440g'
  workspace_name: 'imaging-ml-ws-we'
  cluster: 'training-gpu'
  model_configs_namespace: ''
  extra_code_directory: ''